### ISSUE TITLE
Please move out of this locked platform

### ISSUE THREAD

**Issue by shahab-vahedi** [edlf/DDR5SPDEditor#1]
Would you be so kind in [considering](https://giveupgithub.org/) moving your code somewhere else?

Some alternatives are:

1. [Forgejo](https://forgejo.org/)
2. [Codeberg](https://codeberg.org/)

Otherwise, great acievement! Keep up the good work.

**Comment by edlf** [comment]
Code is also available at codeberg (https://codeberg.org/edlf/DDR5SPDEditor).
